version: '3.4'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    ports:
      - "5432:5432"

  rest-indexer:
    image: lobis/indexer:latest
    environment:
      DATABASE_SCHEMA: pgsql
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
